spring:

  application:
    name: WedSnap

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 400MB

server:
  port: 8080

logging:
  level:
    root: INFO
    me.agfe.wedsnap: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info
