spring:
  profiles:
    active: prod

  application:
    name: WedSnap

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB

  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha
      display-request-duration: true

server:
  port: 8080

logging:
  level:
    root: INFO
    me.agfe.wedsnap: DEBUG
