spring:
  config:
    activate:
      on-profile: local

wedsnap:
  environment: local
  upload:
    base-path: "C:/temp/wedsnap-local"

logging:
  config: classpath:logback-local.xml

app:
  base-url: http://localhost:8080
