spring:
  config:
    activate:
      on-profile: prod

wedsnap:
  environment: prod
  upload:
    base-path: "/nas/wedsnap"

logging:
  config: classpath:logback-prod.xml

app:
  base-url: https://wedsnap.agfe2.synology.me
