app:
  version: ${APP_VERSION:1.0.0}

spring:

  application:
    name: WedSnap

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB

server:
  port: 8080

logging:
  level:
    root: INFO
    me.agfe.wedsnap: DEBUG
